SELECT
    A.CODUSUR,
    B.NOME AS NOME_DO_USUÁRIO,
    A.CODPROD,
    C.DESCRICAO AS DESCRIÇÃO_DO_PRODUTO,
    A.PERCDESCINI,
    A.PERCDESCFIM,
    A.PERCOM,
    A.CODEPTO,
    A.CODSEC
FROM
    PCCOMISSAOUSUR A
JOIN
    PCUSUARI B ON A.CODUSUR = B.CODUSUR
JOIN
    PCPRODUT a ON A.CODPROD = C.CODPROD
ORDER BY
    A.CODUSUR,
    A.PERCDESCINI,
    A.PERCDESCFIM,
    A.PERCOM;
